export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'

export const ADD_AGGREGATOR = 'ADD_AGGREGATOR'
export const ADD_CLICK_TO_AGGREGATOR = 'ADD_CLICK_TO_AGGREGATOR'
export const UPDATE_AGGREGATOR_TO_TIME = 'UPDATE_AGGREGATOR_TO_TIME'
export const UPDATE_AGGREGATORS = 'UPDATE_AGGREGATORS'
export const RETIRE_AGGREGATOR = 'RETIRE_AGGREGATOR'
export const REMOVE_AGGREGATOR = 'REMOVE_AGGREGATOR'

export const UPDATE_USER_COUNT = 'UPDATE_USER_COUNT'
export const UPDATE_ROOM = 'UPDATE_ROOM'
export const UPDATE_ACTIVE_CLICKER_COUNT = 'UPDATE_ACTIVE_CLICKER_COUNT'

export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const REMOVE_USER_NAME = 'REMOVE_USER_NAME'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const CURRENT_NOTIFICATION_COMPLETE = 'CURRENT_NOTIFICATION_COMPLETE'

export const ADD_UPDATE = 'ADD_UPDATE';
export const MOVE_TO_TIME = 'MOVE_TO_TIME';