export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'
export const UPDATE_CHAT_MESSAGE_ID = 'UPDATE_CHAT_MESSAGE_ID'

export const ADD_AGGREGATOR = 'ADD_AGGREGATOR'
export const ADD_CLICK_TO_AGGREGATOR = 'ADD_CLICK_TO_AGGREGATOR'
export const UPDATE_AGGREGATOR_TO_TIME = 'UPDATE_AGGREGATOR_TO_TIME'
export const UPDATE_AGGREGATOR_ID = 'UPDATE_AGGREGATOR_ID'
export const RETIRE_AGGREGATOR = 'RETIRE_AGGREGATOR'

export const UPDATE_USER_COUNT = 'UPDATE_USER_COUNT'
export const UPDATE_ROOM = 'UPDATE_ROOM'

export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'