export const ADD_CHATMESSAGES = 'ADD_CHATMESSAGES'

export const ADD_AGGREGATORS = 'ADD_AGGREGATORS'
export const UPDATE_AGGREGATORS = 'UPDATE_AGGREGATORS'
export const REMOVE_AGGREGATORS = 'REMOVE_AGGREGATORS'
export const UPDATE_AGGREGATOR_SELECT_DESELECT = 'UPDATE_AGGREGATOR_SELECT_DESELECT'
export const RUN_SIMULATIONS_AGGREGATORS = 'RUN_SIMULATIONS_AGGREGATORS'
export const ROLL_BACK_SIMULATIONS_AGGREGATORS = 'ROLL_BACK_SIMULATIONS_AGGREGATORS'

export const UPDATE_USER_COUNT = 'UPDATE_USER_COUNT'
export const UPDATE_ROOM = 'UPDATE_ROOM'
export const UPDATE_ACTIVE_CLICKER_COUNT = 'UPDATE_ACTIVE_CLICKER_COUNT'

export const UPDATE_USER_POINTS = 'UPDATE_USER_POINTS'

export const UPDATE_USER_NAME = 'UPDATE_USER_NAME'
export const REMOVE_USER_NAME = 'REMOVE_USER_NAME'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
export const CURRENT_NOTIFICATION_COMPLETE = 'CURRENT_NOTIFICATION_COMPLETE'

export const SERVER_UPDATE_RECEIVED = 'SERVER_UPDATE_RECEIVED'

export const MOVE_TO_TIME = 'MOVE_TO_TIME'
export const UPDATE_TIME = 'UPDATE_TIME'