export default {
	React : {
		ROOTELEMENTID : "react-root"
	},
	Aggregator : {
		CLICKTIMEOUT : 300,
		FLASHLENGTH : 300,
		CLICKTHRESHOLD : 200,
		INITIALIZATIONTIME : 2000,
		COMPLETEDTIME : 3500,
		RETIREMENTTIME : 400
	}
}