export default {
	React : {
		ROOTELEMENTID : "react-root"
	},
	Aggregator : {
		CLICKTIMEOUT : 300,
		FLASHLENGTH : 300,
		CLICKTHRESHOLD : 200,
		INITIALIZATIONTIME : 50000,
		COMPLETEDTIME : 3500,
		RETIREMENTTIME : 400
	},
	App : {
		BUFFERTIME : 300
	}
}