export const ADD_CHAT_MESSAGE = 'ADD_CHAT_MESSAGE'
export const VOTE_CHAT_MESSAGE = 'VOTE_CHAT_MESSAGE'

export const ADD_AGGREGATOR = 'ADD_AGGREGATOR'
export const ADD_CLICK_TO_AGGREGATOR = 'ADD_CLICK_TO_AGGREGATOR'
export const UPDATE_AGGREGATOR_TO_TIME = 'UPDATE_AGGREGATOR_TO_TIME'