export const simulationData = {
	names : ["Max", "Francis", "Margot", "Zissou", "Suzy", "Eli", "Hennessey", "Royal", "Whitman", "Eleanor", "Raleigh", "Etheline", "Mordecai", "Margaret", "Jane", "Ash", "Ari"],
	debateComments : [
		"Trump: \"You have no idea how many people I've bribed\"",
		"Holy shit Christe's trying so hard to push that 9/11 cred to support the NSA.",
		"IF YOU CAN DODGE A QUESTION YOU CAN DODGE A BALL",
		"I'm enjoying Trump's candidness. Why does this feel so dirty?",
		"Donald Trump for Lord Commander of the Night's Watch!",
		"Jeb Bush called himself \"Veto Corleone.\" Everyone drink.",
		"Trump: \"Every company in Atlantic City is going bankrupt... Chris can tell you about that\"",
		"Lindsay Graham: DARKNESS. NO PARENTS.",
		"Look at Kasich spouting facts instead of talking points, good on him.",
		"Carson, you're black. How are race relations going?",
		"Trump ZERO FUCKS",
		"None of these idiots mention Kasich, and all of them like Cruz. Fuck my party.",
		"Ted Cruz: \"Vote for me, I'm willing to say Voldemort.\"",
		"EL CHAPO NAME DROPPED. IM DYING.",
		"This Kasich guy seems reasonable. Poor guy is fucked.",
		"Did Ben Carson leave?",
		"Does anybody else think Ted Cruz always looks like he's about to burst into tears?",
		"Lindsey is running against Hillary from the GOP B show. Shoot for the stars kid.",
		"Fiorina: I hate what she's saying but I like how she's saying it",
		"John Stewart wishes he had stayed on for another week right about now.",
		"Is John a democrat? Is he lost?",
		"I'd rate Chris Christie's performance a 9/11.",
		"Rick Perry is feeling the confidence from those glasses",
		"Oh shit. This moderator. Not letting Trump go.",
		"The tithing suggestion was so surreal",
		"That was one of the best answers for a Republican on gay marriage I have ever heard.",
		"\"Parts of a Buick...\" Really selling to your audience there.",
		"I bet Trump is just making constant jack-off motions off-screen",
		"Kasich seems to be the sort of Christian that gives Christians a decent name.",
		"Rand Paul ain't backing down.",
		"That's so Ronald Raven",
		"Did Santorum just invoke Dredd Scott?",
		"Did Ben Carson die on stage and just no one decide to acknowledge it?",
		"\"You're having a hard time tonight\" DAMNNN",
		"FOX is trying to bring down Trump, but even they can't contain that persona",
		"John Kasich: INVOKES REAGAN! TAKE A SHOT!",
		"\"I'll give you THREE words... Not good at email!\" - Rick Perry",
		"Ben Carson For Another Republican Debate Question 2015",
		"Really they want us to go back to Iraq? Are they crazy?",
		"Man, are we sure Kasich is a republican?",
		"If I started slapping Cruz's face, I just don't think I could stop.",
		"That Huckabee rant was dystopian",
		"Carson talks like Perd Hapley",
		"I didn't realize 9/11 happened in New Jersey.",
		"Damn, I can get behind Kasich.",
		"Giving the race question to the black guy. Classy.",
		"Interesting the black candidate gets the question on racism............",
		"Kasich is a an intelligent, reasonable guy? What the hell is he doing up there?",
		"I think Fiorina did well. She came off better than the rest.",
		"If you close your eyes you're in an episode of Springer.",
		"Did you know Kasich's dad was a mailman?",
		"Fact checkers are going to have a field day with this shit."
	]
};